### ISSUE TITLE
[API] GET blogs/get/:id 

### ISSUE THREAD

**Issue by Himasnhu-AT** [technobyte-nitkkr/Blogs#10]
get a specific blog based on blogId

**Comment by Debatreya** [comment]
@khushi-rakheja --> Khushhi Rakheja

**Comment by Debatreya** [comment]
2nd Year: 
- For any doubt discuss with your senior as mentioned above
- Discussions to be done in this issue thread or may be in DMs.
@OjuIsOn
@RajvanshMalhotra

**Comment by RajvanshMalhotra** [comment]
hi i am rajvansh

**Comment by OjuIsOn** [comment]
Hi! I am Ojasvi

**Comment by khushi-rakheja** [comment]
https://github.com/khushi-rakheja/Blogs

@RajvanshMalhotra @OjuIsOn fork the above repo

**Comment by Debatreya** [comment]
@OjuIsOn  and @RajvanshMalhotra 
great collaboration guys.

@khushi-rakheja if the wok is done, please create a PR to Himanshu's repo.

**Comment by Debatreya** [comment]
Issue resolved. Close kr de

@Himasnhu-AT
