### ISSUE TITLE
[API] POST blogs/comment/:id 

### ISSUE THREAD

**Issue by Himasnhu-AT** [technobyte-nitkkr/Blogs#12]
add comment to blog

req:
```
header: {
  auth_token: <user_auth_token>
} // passed using cookie
body: {
  content: string
}
```

**Comment by Debatreya** [comment]
@vishnoiyashraj25 --> Yash Raj Vishnoi

**Comment by shikhar2k4** [comment]
Hey sir, I am shikhar, from AI&ML branch.

**Comment by yash-shakya** [comment]
Hello, I'm Yash Shakya, from CS

**Comment by vishnoiyashraj25** [comment]
Hii @yash-shakya @shikhar2k4 
Fork this repo: https://github.com/vishnoiyashraj25/Blogs

**Comment by Himasnhu-AT** [comment]
Great work guys
