### ISSUE TITLE
[API] GET blog/search/tags=...?time=...?query=... tag2?time=2020-01-01?query=hello

### ISSUE THREAD

**Issue by Himasnhu-AT** [technobyte-nitkkr/Blogs#13]
Search blog based on a query such as tags, time uploaded, search query string

**Comment by Debatreya** [comment]
@Ansh-Garg22 --> Ansh Garg

**Comment by Debatreya** [comment]
2nd Year: 
- For any doubt discuss with your senior as mentioned above
- Discussions to be done in this issue thread or may be in DMs.
@ranveer193
@ayush-3107

**Comment by ayush-3107** [comment]
Hi, I am Ayush Singhal

**Comment by Ansh-Garg22** [comment]
Hello @ayush-3107 @ranveer193

We can start working on the blogs issue. Here is the forked repository: https://github.com/Ansh-Garg22/Blogs.

Please fork this repository into your GitHub account and clone it to VS Code as we discussed in our meeting earlier. Start working on the issue, and if you encounter any difficulties, please reach out to me.

**Comment by Ansh-Garg22** [comment]
Any updates? @ranveer193 @ayush-3107

**Comment by Debatreya** [comment]
@Ansh-Garg22 dkh le khud kr skta hain toh, Otherwise mujhe bolna, 1-2 jnrs free hain
Ya fer mein hi help kr dunga

**Comment by Debatreya** [comment]
Just a little brief on this issue.

You will get an object of the query from req.query;
{
 tags: (may not be present, may have multiple tags) null | string | string[]
 time?: Date 
 query?: string | null (you have to do some splitting and match the words with those present in Blogs DB
 }
 
 Checkout some good methods of searching..

**Comment by Debatreya** [comment]
This issue is resolved.

@Himasnhu-AT
