### ISSUE TITLE
[API] POST admin

### ISSUE THREAD

**Issue by Himasnhu-AT** [technobyte-nitkkr/Blogs#15]
@@ADMIN ONLY

#### Workflow to ensure admin only access this:

```js
// get auth_token from cookie

const { userId, email } = requestDataFromJWTToken(auth_token)

const user = findUniqueUser(id, email)

if ( user.type != admin) 
  return 'Unauthorized'

// continue
```

**Comment by Debatreya** [comment]
@Debatreya

**Comment by Debatreya** [comment]
2nd Year: 
- For any doubt discuss with your senior as mentioned above
- Discussions to be done in this issue thread or may be in DMs.
@nototiger0227
@MuditGargg

**Comment by nototiger0227** [comment]
Hi! I am Vansh Gupta.

**Comment by MuditGargg** [comment]
Hii! I am Mudit Garg

**Comment by Debatreya** [comment]
Hi, Vansh and Mudit.
Go throught the dev-docs rn, we will clear every thing in the meet tomorrow.

dev-docs.md

**Comment by Debatreya** [comment]
https://github.com/Debatreya/Blogs

@MuditGargg @nototiger0227 Fork this repo☝️

**Comment by Debatreya** [comment]
@Himasnhu-AT yeh ek middleware hain nah??

**Comment by Himasnhu-AT** [comment]
@Debatreya yup. But here's what it should return:

- All the published blogs
- All the blogs where review = pending
- All the blogs where review = update

Format:

```json
{
    "published_blogs": [],
    "review": [],
    "updated_review": []
}
```

**Comment by Debatreya** [comment]
Okay. Great...

**Comment by Debatreya** [comment]
@nototiger0227 @MuditGargg fork nhi Kiya abhi bhi?

**Comment by nototiger0227** [comment]
Hi!,I've read the docs and I've understood working of the project also.

What is this code given in this comment for?
https://github.com/technobyte-nitkkr/Blogs/issues/15#issue-2321546332

As much as I've understood,I think this is the required logic to be implemented in JS to provide admin only access . But I don't know where to put this code in our project files ?

**Comment by Debatreya** [comment]
Yeh. Let's have a meet tomorrow.
When will you be free?

**Comment by nototiger0227** [comment]
Lets meet at 11am?

**Comment by Debatreya** [comment]
> Lets meet at 11am?
> 

Fine: 
[Meet](meet.new)
Click on it. And share the link here..

**Comment by nototiger0227** [comment]
Sir, This creates a new issue?
![image](https://github.com/technobyte-nitkkr/Blogs/assets/159013185/74f289be-9967-4d02-9aa7-8d55791db7e3)

**Comment by Debatreya** [comment]
> Sir, This creates a new issue?
> ![image](https://github.com/technobyte-nitkkr/Blogs/assets/159013185/74f289be-9967-4d02-9aa7-8d55791db7e3)
> 

Koi ni close kr dunga

**Comment by nototiger0227** [comment]
Sir yehi karna tha na?

**Comment by nototiger0227** [comment]
> > Sir, This creates a new issue?
> > ![image](https://private-user-images.githubusercontent.com/159013185/342201567-74f289be-9967-4d02-9aa7-8d55791db7e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMDM3NDYsIm5iZiI6MTcxOTIwMzQ0NiwicGF0aCI6Ii8xNTkwMTMxODUvMzQyMjAxNTY3LTc0ZjI4OWJlLTk5NjctNGQwMi05YWE3LThkNTU3OTFkYjdlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQwNDMwNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYmQ5YWMwMDQyNGU3OGFmODczMDVmNTA4NDkxMGViZDQxMjYzMWNlMjdlM2Q3ZGZiYjYzOGExZWVkMTY0YjNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cgh3ot31dzIBtO_bkkQ3mSJYIG2krEia9r2dpc8O4Vc)
> 
> Koi ni close kr dunga

okay sir

**Comment by Debatreya** [comment]
> Sir yehi karna tha na?
> 

Koi ni, mujhe bhi pta nhi.

Actually meet.new se new gmeet create ho jati hain. 
Mein bhi pehli baar kr rha hu

**Comment by nototiger0227** [comment]
> > Sir yehi karna tha na?
> 
> Koi ni, mujhe bhi pta nhi.
> 
> Actually meet.new se new gmeet create ho jati hain. Mein bhi pehli baar kr rha hu

Ok sir

**Comment by Debatreya** [comment]
@nototiger0227 what's the status?

**Comment by Debatreya** [comment]
Create a PR by tomorrow 12

**Comment by RiyaRaj28** [comment]
> @Debatreya and @Himasnhu-AT sir I've read the docs and I've understood logical working of the project also.
> 
> What is this code given in this comment for? [#15 (comment)](https://github.com/technobyte-nitkkr/Blogs/issues/15#issue-2321546332)
> 
> As much as I've understood,I think this is the required logic to be implemented in JS to provide admin only access . But I don't know where to put this code in our project files ?


@Debatreya sir
 I've this same doubt

**Comment by Debatreya** [comment]
Hi @RiyaRaj28 , in which issue are you working on? Does it depend on this ?

**Comment by Debatreya** [comment]
> > @Debatreya and @Himasnhu-AT sir I've read the docs and I've understood logical working of the project also.
> > What is this code given in this comment for? [#15 (comment)](https://github.com/technobyte-nitkkr/Blogs/issues/15#issue-2321546332)
> > As much as I've understood,I think this is the required logic to be implemented in JS to provide admin only access . But I don't know where to put this code in our project files ?
> 
> @Debatreya sir I've this same doubt

Mostly, The modules are independent, 
but if you have this doubt, ig its better to have a meet tomorrow,
- @RiyaRaj28 
- @Saanvi26

**Comment by RiyaRaj28** [comment]
> Hi @RiyaRaj28 , in which issue are you working on? Does it depend on this ?

Yes sir, I've been assigned issue 16 and it depends on this. Okay, I'm up for the meet whenever you say.

**Comment by Debatreya** [comment]
@MuditGargg hi bro? What's going on?
Will you be working on this or want to have a glimpse of what's going on?.?

We are having a meet today noon. Feel free to contact me if you are willing.

**Comment by MuditGargg** [comment]
Hello @Debatreya sir. Sorry for being inactive for the past few weeks.
 I haven't been able to work due to some reasons.
 I'll try to join the meeting today and catch up with everything that's going on.

**Comment by RiyaRaj28** [comment]
> > > Hi @RiyaRaj28 , in which issue are you working on? Does it depend on this ?
> > 
> > 
> > Yes sir, I've been assigned issue 16 and it depends on this. Okay, I'm up for the meet whenever you say.
> 
> Sure. After Lunch, 2pm afterwards. @Saanvi26 would you like to join?

Okay, at 2.30?

**Comment by Debatreya** [comment]
@RiyaRaj28 @MuditGargg 
I will dm you the link.

**Comment by RiyaRaj28** [comment]
> @RiyaRaj28 @MuditGargg I will dm you the link.

okay

**Comment by Himasnhu-AT** [comment]
@nototiger0227 close the pl #35 

Great work guys on closing this issue :)
