### ISSUE TITLE
[API] POST admin/blog/review/:id

### ISSUE THREAD

**Issue by Himasnhu-AT** [technobyte-nitkkr/Blogs#16]
@@Admin

Ensure user is admin based on #15 

send review of blog based on:

- `pending`: no review done
- `approved`: blog is published for everyone
- `update`: improve blog based on `review_message`

**Comment by Debatreya** [comment]
@Saanvi26 --> Saanvi

**Comment by Debatreya** [comment]
2nd Year: 
- For any doubt discuss with your senior as mentioned above
- Discussions to be done in this issue thread or may be in DMs.
@Gourish18
@RiyaRaj28

**Comment by Gourish18** [comment]
Hi, I am Gourish

**Comment by RiyaRaj28** [comment]
Hello, Riya here

**Comment by Saanvi26** [comment]
Hi @RiyaRaj28 and @Gourish18 !
Go through [dev-docs.md](https://github.com/technobyte-nitkkr/Blogs/blob/main/dev-docs.md) in the meantime .

**Comment by RiyaRaj28** [comment]
Okay sure
