### ISSUE TITLE
[API] GET admin/blog/delete/:id

### ISSUE THREAD

**Issue by Himasnhu-AT** [technobyte-nitkkr/Blogs#17]
@@Admin

Ensure the user is admin based on https://github.com/technobyte-nitkkr/Blogs/issues/15

Delete blog based on id

**Comment by Debatreya** [comment]
@mayanksinghshekhawat --> Mayank Shekhawat

**Comment by Debatreya** [comment]
2nd Year: 
- For any doubt discuss with your senior as mentioned above
- Discussions to be done in this issue thread or may be in DMs.
@TheDisciple786

**Comment by TheDisciple786** [comment]
sir I am pretty unclear, do I have to introduce myself first?

**Comment by Debatreya** [comment]
Hi, I am <name>
just this
