### ISSUE TITLE
[API] POST admin/newsletter

### ISSUE THREAD

**Issue by Himasnhu-AT** [technobyte-nitkkr/Blogs#18]
@@Admin

Ensure user is admin based on https://github.com/technobyte-nitkkr/Blogs/issues/15

send newsletter to all user who are subscribbed

**Comment by Debatreya** [comment]
@Zolo-Ryan --> Utkarsh

**Comment by Debatreya** [comment]
2nd Year: 
- For any doubt discuss with your senior as mentioned above
- Discussions to be done in this issue thread or may be in DMs.
@Nancy-byte

**Comment by Nancy-byte** [comment]
Hello! This is Nancy Goel.

**Comment by Nancy-byte** [comment]
Hello! This is Nancy Goel.

**Comment by Zolo-Ryan** [comment]
Hello @Nancy-byte , fork this repo: https://github.com/Zolo-Ryan/Blogs
