### ISSUE TITLE
[API] integrate Google OAuth

### ISSUE THREAD

**Issue by Himasnhu-AT** [technobyte-nitkkr/Blogs#7]
Integration of Google OAuth with jwt token for authentication verification

##### Public API's: accessed by all
- [ ] /auth/signin
- [ ] /auth/signup

##### Authenticated user:
- [ ] /auth/logout

#### How to ensure that the user is authenticated or not?

Store cookie in client-side with key-value pair: auth_token: <auth_token>

**Comment by Debatreya** [comment]
Assign me

**Comment by Himasnhu-AT** [comment]
@Debatreya , already implemented it, will make  pr after checking code safety
