### ISSUE TITLE
[API] Get /newsletter/email 

### ISSUE THREAD

**Issue by Himasnhu-AT** [technobyte-nitkkr/Blogs#8]
Sign up email for the newsletter

**Comment by Debatreya** [comment]
@mayank2393 -> Mayank Tripathi

**Comment by Debatreya** [comment]
2nd Year: 
- For any doubt discuss with your senior as mentioned above
- Discussions to be done in this issue thread or may be in DMs.
@ArnavSharma005
@ashiraj628

**Comment by ashiraj628** [comment]
Hi, I am Ashish Yadav

**Comment by ArnavSharma005** [comment]
Hi, I am Arnav Sharma

**Comment by mayank2393** [comment]
Hello @ArnavSharma005 @ashiraj628 , Guys Fork this Repository : https://github.com/mayank2393/Blogs

**Comment by mayank2393** [comment]
@ArnavSharma005 bro as of now Nodemailer me apne khud ke secrets use krlo  env file baad me update hojaygi, and with that mock database calls kro, like Mongo se database ki appropriate table call krke get lots of email ids aur unsab par email send krlo loop me,

**Comment by Debatreya** [comment]
Its done nah??
@mayank2393 or @Himasnhu-AT 
Close it then.

**Comment by Himasnhu-AT** [comment]
didnt link the issue ig :)
